package bitcoin

import (
	"bytes"
	"testing"

	btcec2 "github.com/btcsuite/btcd/btcec/v2"
	"github.com/btcsuite/btcd/btcec/v2/schnorr"
	"github.com/btcsuite/btcd/txscript"
)

// The taproot helpers in taproot.go are a from-scratch BIP-341 implementation
// over raw secp256k1 field and scalar operations. The other tests in this package
// pin them to fixtures that were generated by this same implementation, so they
// detect a later regression but cannot detect an original error. That matters more
// than usual here: a wrong output key produces a well-formed address whose coins
// nobody can ever spend, so the failure mode is fund loss rather than a rejected
// transaction.
//
// These tests cross-check against btcd's txscript, an independent and widely used
// implementation already in this module's dependency graph, over many generated
// inputs rather than a handful of constants. Any divergence in the tweak
// derivation, the point addition, or the x-only serialisation shows up here.

// TestTaprootOutputKeyMatchesTxscriptScriptPath cross-checks the script-path
// (merkle root present) derivation.
func TestTaprootOutputKeyMatchesTxscriptScriptPath(t *testing.T) {
	for i := range 128 {
		privateKey, err := btcec2.NewPrivateKey()
		if err != nil {
			t.Fatal(err)
		}

		var internalKey [32]byte
		copy(internalKey[:], schnorr.SerializePubKey(privateKey.PubKey()))

		// Vary the leaf script so the merkle root differs on every iteration.
		leafScript := append(
			[]byte{txscript.OP_DATA_1, byte(i)},
			txscript.OP_DROP, txscript.OP_TRUE,
		)

		merkleRoot, err := TaprootLeafHash(Script(leafScript))
		if err != nil {
			t.Fatal(err)
		}

		// Independently confirm the leaf hash itself, not just the output key: an
		// error here would otherwise cancel out on both sides below.
		expectedLeafHash := txscript.NewBaseTapLeaf(leafScript).TapHash()
		if !bytes.Equal(merkleRoot[:], expectedLeafHash[:]) {
			t.Fatalf(
				"iteration %d: leaf hash mismatch: ours [%x], txscript [%x]",
				i, merkleRoot, expectedLeafHash,
			)
		}

		ours, err := TaprootOutputKey(internalKey, &merkleRoot)
		if err != nil {
			t.Fatal(err)
		}

		theirs := txscript.ComputeTaprootOutputKey(
			privateKey.PubKey(),
			merkleRoot[:],
		)
		expected := schnorr.SerializePubKey(theirs)

		if !bytes.Equal(ours[:], expected) {
			t.Fatalf(
				"iteration %d: output key mismatch: ours [%x], txscript [%x]",
				i, ours, expected,
			)
		}
	}
}

// TestTaprootOutputKeyMatchesTxscriptKeyPathOnly cross-checks the key-path-only
// derivation (no script tree). This is the case tBTC FROST wallets actually use,
// so it is the one that must be right for real funds.
func TestTaprootOutputKeyMatchesTxscriptKeyPathOnly(t *testing.T) {
	for i := range 128 {
		privateKey, err := btcec2.NewPrivateKey()
		if err != nil {
			t.Fatal(err)
		}

		var internalKey [32]byte
		copy(internalKey[:], schnorr.SerializePubKey(privateKey.PubKey()))

		ours, err := TaprootOutputKey(internalKey, nil)
		if err != nil {
			t.Fatal(err)
		}

		// A nil scriptRoot selects txscript's key-path-only tweak, matching the
		// nil merkleRoot above.
		theirs := txscript.ComputeTaprootKeyNoScript(privateKey.PubKey())
		expected := schnorr.SerializePubKey(theirs)

		if !bytes.Equal(ours[:], expected) {
			t.Fatalf(
				"iteration %d: key-path output key mismatch: ours [%x], txscript [%x]",
				i, ours, expected,
			)
		}
	}
}

// TestPayToTaprootWithScriptTreeMatchesTxscript checks the whole script-building
// path, so a correct output key cannot be undone by wrong script framing (the
// OP_1 witness-version prefix and 32-byte push).
func TestPayToTaprootWithScriptTreeMatchesTxscript(t *testing.T) {
	privateKey, err := btcec2.NewPrivateKey()
	if err != nil {
		t.Fatal(err)
	}

	var internalKey [32]byte
	copy(internalKey[:], schnorr.SerializePubKey(privateKey.PubKey()))

	leafScript := []byte{txscript.OP_TRUE}
	merkleRoot, err := TaprootLeafHash(Script(leafScript))
	if err != nil {
		t.Fatal(err)
	}

	ours, err := PayToTaprootWithScriptTree(internalKey, merkleRoot)
	if err != nil {
		t.Fatal(err)
	}

	outputKey := txscript.ComputeTaprootOutputKey(
		privateKey.PubKey(),
		merkleRoot[:],
	)
	theirs, err := txscript.PayToTaprootScript(outputKey)
	if err != nil {
		t.Fatal(err)
	}

	if !bytes.Equal(ours, theirs) {
		t.Fatalf("P2TR script mismatch: ours [%x], txscript [%x]", ours, theirs)
	}
}
