//go:build frost_native

package signing

import (
	"errors"
	"fmt"
)

// attemptContextHashCarrier is implemented by every protocol
// message type that carries the optional AttemptContextHash field
// introduced in RFC-21 Phase 1B. The validation helper below uses
// the interface so a single implementation covers all three
// FROST/tbtc-signer message types without duplicating per-type
// logic.
type attemptContextHashCarrier interface {
	// GetAttemptContextHash returns the message's hash and a
	// presence flag. Implementations are generated by the per-type
	// Set/Get helpers in attempt_context_binding.go.
	GetAttemptContextHash() ([AttemptContextHashFieldLength]byte, bool)
}

// ErrAttemptContextHashMissing is returned when a message lacks
// the AttemptContextHash field while the session is bound to a
// ROAST attempt that requires it. Distinct sentinel so callers
// can map it to a specific RecordReject reason.
var ErrAttemptContextHashMissing = errors.New(
	"attempt context hash required: session is ROAST-active but message omits the binding field",
)

// ErrAttemptContextHashMismatch is returned when a message's
// AttemptContextHash does not match the session's currently-bound
// AttemptContext.Hash(). The peer is either talking about a stale
// attempt (post-transition) or trying to inject a message for a
// different context.
var ErrAttemptContextHashMismatch = errors.New(
	"attempt context hash mismatch: message bound to a different attempt",
)

// verifyMessageAttemptContextHash enforces the RFC-21 Phase-6
// milestone that promotes the AttemptContextHash field from
// optional to required at the receive boundary, but only when the
// session has a ROAST-attempt binding registered.
//
// When no session-handle binding exists for sessionID (the typical
// state for non-ROAST sessions and for default builds), this
// function returns nil and lets the message through. The receive
// loop's other gates (shouldAcceptNativeFROSTMessage, etc.) still
// apply.
//
// When a binding exists -- i.e. the orchestration layer has begun
// an attempt for this session and is expecting the receive loops
// to participate -- the message must carry an AttemptContextHash
// that equals the bound context's Hash(). Returns
// ErrAttemptContextHashMissing or ErrAttemptContextHashMismatch on
// failure so the caller can RecordReject with a precise reason.
func verifyMessageAttemptContextHash(
	msg attemptContextHashCarrier,
	sessionID string,
) error {
	_, ctx, ok := currentAttemptHandleForCollect(sessionID)
	if !ok {
		// No binding: legacy / non-ROAST mode. Skip enforcement
		// so default builds and non-ROAST sessions stay
		// observationally identical to pre-Phase-6 behaviour.
		return nil
	}
	msgHash, present := msg.GetAttemptContextHash()
	if !present {
		return ErrAttemptContextHashMissing
	}
	expected := ctx.Hash()
	if msgHash != expected {
		return fmt.Errorf(
			"%w: message=%x, current attempt=%x",
			ErrAttemptContextHashMismatch,
			msgHash[:4],
			expected[:4],
		)
	}
	return nil
}
