// Package spv implements the proof-maintenance half of the tBTC wallet-action
// domain. For each wallet action whose transaction has been executed on Bitcoin
// (deposit sweep, redemption, moving funds, moved funds sweep) it finds the
// unproven transactions and submits their SPV proofs to the host chain.
//
// Its counterpart is pkg/tbtcpg, the proposal-generation half, which decides
// which actions a wallet should take. The two packages deliberately mirror
// each other's file layout: a file here (deposit_sweep.go, redemptions.go,
// moving_funds.go, moved_funds_sweep.go) proves the transaction produced by
// the action whose proposal is generated by the same-named file there.
package spv

import (
	"bytes"
	"context"
	"encoding/hex"
	"fmt"
	"math/big"
	"time"

	"github.com/keep-network/keep-core/pkg/tbtc"

	"github.com/ipfs/go-log/v2"

	"github.com/keep-network/keep-core/pkg/bitcoin"
	"github.com/keep-network/keep-core/pkg/maintainer/btcdiff"
)

var logger = log.Logger("keep-maintainer-spv")

// The length of the Bitcoin difficulty epoch in blocks.
const difficultyEpochLength = 2016

// The maximum number of block headers allowed in a single SPV proof. Bounds
// the forward walk over headers when computing required confirmations
// (relevant on testnet4 where long runs of minimum-difficulty blocks occur).
const maxProofHeaders = 144

func Initialize(
	ctx context.Context,
	config Config,
	spvChain Chain,
	btcDiffChain btcdiff.Chain,
	btcChain bitcoin.Chain,
) {
	spvMaintainer := &spvMaintainer{
		config:       config,
		spvChain:     spvChain,
		btcDiffChain: btcDiffChain,
		btcChain:     btcChain,
	}

	go spvMaintainer.startControlLoop(ctx)
}

// proofTypes holds the information about proof types supported by the
// SPV maintainer.
var proofTypes = map[tbtc.WalletActionType]struct {
	unprovenTransactionsGetter unprovenTransactionsGetter
	transactionProofSubmitter  transactionProofSubmitter
}{
	tbtc.ActionDepositSweep: {
		unprovenTransactionsGetter: getUnprovenDepositSweepTransactions,
		transactionProofSubmitter:  SubmitDepositSweepProof,
	},
	tbtc.ActionRedemption: {
		unprovenTransactionsGetter: getUnprovenRedemptionTransactions,
		transactionProofSubmitter:  SubmitRedemptionProof,
	},
	tbtc.ActionMovingFunds: {
		unprovenTransactionsGetter: getUnprovenMovingFundsTransactions,
		transactionProofSubmitter:  SubmitMovingFundsProof,
	},
	tbtc.ActionMovedFundsSweep: {
		unprovenTransactionsGetter: getUnprovenMovedFundsSweepTransactions,
		transactionProofSubmitter:  SubmitMovedFundsSweepProof,
	},
}

type spvMaintainer struct {
	config       Config
	spvChain     Chain
	btcDiffChain btcdiff.Chain
	btcChain     bitcoin.Chain
}

func (sm *spvMaintainer) startControlLoop(ctx context.Context) {
	logger.Info("starting SPV maintainer")

	defer func() {
		logger.Info("stopping SPV maintainer")
	}()

	for {
		err := sm.maintainSpv(ctx)
		if err != nil {
			logger.Errorf(
				"error while maintaining SPV: [%v]; restarting maintainer",
				err,
			)
		}

		select {
		case <-time.After(sm.config.RestartBackoffTime):
		case <-ctx.Done():
			return
		}
	}
}

func (sm *spvMaintainer) maintainSpv(ctx context.Context) error {
	for {
		for action, v := range proofTypes {
			logger.Infof("starting [%s] proof task execution...", action)

			if err := sm.proveTransactions(
				v.unprovenTransactionsGetter,
				v.transactionProofSubmitter,
			); err != nil {
				return fmt.Errorf(
					"error while proving [%s] transactions: [%v]",
					action,
					err,
				)
			}

			logger.Infof("[%s] proof task completed", action)
		}

		logger.Infof(
			"proof tasks completed; next run in [%s]",
			sm.config.IdleBackoffTime,
		)

		select {
		case <-time.After(sm.config.IdleBackoffTime):
		case <-ctx.Done():
			return ctx.Err()
		}
	}
}

// unprovenTransactionsGetter is a type representing a function that is
// used to get unproven Bitcoin transactions.
type unprovenTransactionsGetter func(
	historyDepth uint64,
	transactionLimit int,
	btcChain bitcoin.Chain,
	spvChain Chain,
) (
	[]*bitcoin.Transaction,
	error,
)

// transactionProofSubmitter is a type representing a function that is used
// to submit the constructed SPV proof to the host chain.
type transactionProofSubmitter func(
	transactionHash bitcoin.Hash,
	requiredConfirmations uint,
	btcChain bitcoin.Chain,
	spvChain Chain,
) error

// proveTransactions gets unproven Bitcoin transactions using the provided
// unprovenTransactionsGetter, build the SPV proofs, and submits them using
// the provided transactionProofSubmitter.
func (sm *spvMaintainer) proveTransactions(
	unprovenTransactionsGetter unprovenTransactionsGetter,
	transactionProofSubmitter transactionProofSubmitter,
) error {
	transactions, err := unprovenTransactionsGetter(
		sm.config.HistoryDepth,
		sm.config.TransactionLimit,
		sm.btcChain,
		sm.spvChain,
	)
	if err != nil {
		return fmt.Errorf("failed to get unproven transactions: [%v]", err)
	}

	logger.Infof("found [%d] unproven transaction(s)", len(transactions))

	for _, transaction := range transactions {
		// Print the transaction in the same endianness as block explorers do.
		transactionHashStr := transaction.Hash().Hex(bitcoin.ReversedByteOrder)

		logger.Infof(
			"proceeding with proof for transaction [%s]",
			transactionHashStr,
		)

		isProofWithinRelayRange, accumulatedConfirmations, requiredConfirmations, err := getProofInfo(
			transaction.Hash(),
			sm.btcChain,
			sm.spvChain,
			sm.btcDiffChain,
		)
		if err != nil {
			return fmt.Errorf("failed to get proof info: [%v]", err)
		}

		if !isProofWithinRelayRange {
			// The required proof goes outside the previous and current
			// difficulty epochs as seen by the relay. Skip the transaction. It
			// will most likely be proven later.
			logger.Warnf(
				"skipped proving transaction [%s]; the range "+
					"of the required proof goes outside the previous and "+
					"current difficulty epochs as seen by the relay",
				transactionHashStr,
			)
			continue
		}

		if accumulatedConfirmations < requiredConfirmations {
			// Skip the transaction as it has not accumulated enough
			// confirmations. It will be proven later.
			logger.Infof(
				"skipped proving transaction [%s]; transaction "+
					"has [%v/%v] confirmations",
				transactionHashStr,
				accumulatedConfirmations,
				requiredConfirmations,
			)
			continue
		}

		err = transactionProofSubmitter(
			transaction.Hash(),
			requiredConfirmations,
			sm.btcChain,
			sm.spvChain,
		)
		if err != nil {
			return err
		}

		logger.Infof(
			"successfully submitted proof for transaction [%s]",
			transactionHashStr,
		)
	}

	logger.Infof("finished round of proving transactions")

	return nil
}

func isInputCurrentWalletsMainUTXO(
	fundingTxHash bitcoin.Hash,
	fundingOutputIndex uint32,
	walletPublicKeyHash [20]byte,
	btcChain bitcoin.Chain,
	spvChain Chain,
) (bool, error) {
	// Get the transaction the input originated from to calculate the input value.
	previousTransaction, err := btcChain.GetTransaction(fundingTxHash)
	if err != nil {
		return false, fmt.Errorf("failed to get previous transaction: [%v]", err)
	}
	if fundingOutputIndex >= uint32(len(previousTransaction.Outputs)) {
		return false, fmt.Errorf(
			"funding output index [%d] out of range for transaction [%s] "+
				"with [%d] outputs",
			fundingOutputIndex,
			fundingTxHash.String(),
			len(previousTransaction.Outputs),
		)
	}
	fundingOutputValue := previousTransaction.Outputs[fundingOutputIndex].Value

	// Assume the input is the main UTXO and calculate hash.
	mainUtxoHash := spvChain.ComputeMainUtxoHash(&bitcoin.UnspentTransactionOutput{
		Outpoint: &bitcoin.TransactionOutpoint{
			TransactionHash: fundingTxHash,
			OutputIndex:     fundingOutputIndex,
		},
		Value: fundingOutputValue,
	})

	// Get the wallet and check if its main UTXO matches the calculated hash.
	wallet, err := spvChain.GetWallet(walletPublicKeyHash)
	if err != nil {
		return false, fmt.Errorf("failed to get wallet: [%v]", err)
	}

	return bytes.Equal(mainUtxoHash[:], wallet.MainUtxoHash[:]), nil
}

// getProofInfo returns information about the SPV proof. It includes the
// information whether the transaction proof range is within the previous and
// current difficulty epochs as seen by the relay, the accumulated number of
// confirmations and the required number of confirmations.
func getProofInfo(
	transactionHash bitcoin.Hash,
	btcChain bitcoin.Chain,
	spvChain Chain,
	btcDiffChain btcdiff.Chain,
) (
	bool, uint, uint, error,
) {
	latestBlockHeight, err := btcChain.GetLatestBlockHeight()
	if err != nil {
		return false, 0, 0, fmt.Errorf(
			"failed to get latest block height: [%v]",
			err,
		)
	}

	accumulatedConfirmations, err := btcChain.GetTransactionConfirmations(
		transactionHash,
	)
	if err != nil {
		return false, 0, 0, fmt.Errorf(
			"failed to get transaction confirmations: [%v]",
			err,
		)
	}

	txProofDifficultyFactor, err := spvChain.TxProofDifficultyFactor()
	if err != nil {
		return false, 0, 0, fmt.Errorf(
			"failed to get transaction proof difficulty factor: [%v]",
			err,
		)
	}

	currentEpochDifficulty, previousEpochDifficulty, err :=
		btcDiffChain.GetCurrentAndPrevEpochDifficulty()
	if err != nil {
		return false, 0, 0, fmt.Errorf(
			"failed to get Bitcoin epoch difficulties: [%v]",
			err,
		)
	}

	// Calculate the starting block of the proof.
	proofStartBlock := uint64(latestBlockHeight - accumulatedConfirmations + 1)

	// Walk the header chain forward, mirroring the Bridge's
	// BitcoinTx.determineRequestedDifficulty and evaluateProofDifficulty
	// behavior:
	// - minimum-difficulty (DIFF1) headers are skipped while looking for the
	//   decisive header, but only when both relay epoch difficulties are
	//   above minimum (testnet4 BIP94 blocks in real epochs),
	// - the first decisive header must match the relay's current or previous
	//   epoch difficulty; that value becomes the requested difficulty,
	// - headers are accumulated until their total observed difficulty reaches
	//   requested difficulty times the transaction proof difficulty factor.
	one := big.NewInt(1)
	skipMinDifficulty := currentEpochDifficulty.Cmp(one) > 0 &&
		previousEpochDifficulty.Cmp(one) > 0

	var requestedDiff *big.Int
	observedDiff := big.NewInt(0)
	headerCount := uint(0)

	for {
		if headerCount >= maxProofHeaders {
			// Could not find a decisive header or accumulate enough
			// difficulty within a sane number of headers. Skip the
			// transaction; it may become provable later.
			return false, 0, 0, nil
		}

		blockHeight := proofStartBlock + uint64(headerCount)
		if blockHeight > uint64(latestBlockHeight) {
			// Not enough mined blocks yet to assemble the proof. Report the
			// number of headers needed so far plus one more; the caller will
			// see accumulated < required and skip the transaction for now.
			return true, accumulatedConfirmations, headerCount + 1, nil
		}

		header, err := btcChain.GetBlockHeader(uint(blockHeight))
		if err != nil {
			return false, 0, 0, fmt.Errorf(
				"failed to get block header at height [%v]: [%v]",
				blockHeight,
				err,
			)
		}

		headerDiff := header.Difficulty()
		headerCount++
		observedDiff.Add(observedDiff, headerDiff)

		if requestedDiff == nil {
			// Still looking for the decisive header.
			if skipMinDifficulty && headerDiff.Cmp(one) == 0 {
				continue
			}

			if headerDiff.Cmp(currentEpochDifficulty) == 0 {
				requestedDiff = currentEpochDifficulty
			} else if headerDiff.Cmp(previousEpochDifficulty) == 0 {
				requestedDiff = previousEpochDifficulty
			} else {
				// The Bridge would revert with "Not at current or previous
				// difficulty". The transaction is either too fresh (its epoch
				// is not yet proven in the relay) or too old. Skip it; it may
				// be proven in the future.
				return false, 0, 0, nil
			}
		}

		totalDifficultyRequired := new(big.Int).Mul(
			requestedDiff,
			txProofDifficultyFactor,
		)
		if observedDiff.Cmp(totalDifficultyRequired) >= 0 {
			return true, accumulatedConfirmations, headerCount, nil
		}
	}
}

// walletEvent is a type constraint representing wallet-related chain events.
type walletEvent interface {
	GetWalletPublicKeyHash() [20]byte
}

// uniqueWalletPublicKeyHashes parses the list of wallet-related events and
// returns a list of unique wallet public key hashes.
func uniqueWalletPublicKeyHashes[T walletEvent](events []T) [][20]byte {
	cache := make(map[string]struct{})
	var publicKeyHashes [][20]byte

	for _, event := range events {
		key := event.GetWalletPublicKeyHash()
		strKey := hex.EncodeToString(key[:])

		// Check for uniqueness
		if _, exists := cache[strKey]; !exists {
			cache[strKey] = struct{}{}
			publicKeyHashes = append(publicKeyHashes, key)
		}
	}

	return publicKeyHashes
}

// unprovenSearchStartBlock returns the starting block of the range in which
// the events used to find unproven transactions are searched for. It is
// derived from the current chain tip and the configured history depth.
func unprovenSearchStartBlock(
	historyDepth uint64,
	spvChain Chain,
) (uint64, error) {
	blockCounter, err := spvChain.BlockCounter()
	if err != nil {
		return 0, fmt.Errorf("failed to get block counter: [%v]", err)
	}

	currentBlock, err := blockCounter.CurrentBlock()
	if err != nil {
		return 0, fmt.Errorf("failed to get current block: [%v]", err)
	}

	// Guard against unsigned underflow on short chains (e.g. early test
	// networks) where the configured history depth can exceed the current
	// tip; clamp the search start to the genesis block instead of wrapping
	// around to a near-maximum block number.
	if historyDepth > currentBlock {
		return 0, nil
	}

	return currentBlock - historyDepth, nil
}

// collectUnprovenWalletTransactions returns the recent transactions of the
// wallet identified by lookupPublicKeyHash that satisfy the isUnproven
// predicate. When stopAtFirstMatch is true it returns as soon as the first
// matching transaction is found, which is sufficient for wallet operations
// that can have at most one unproven transaction at a time.
func collectUnprovenWalletTransactions(
	lookupPublicKeyHash [20]byte,
	transactionLimit int,
	btcChain bitcoin.Chain,
	isUnproven func(transaction *bitcoin.Transaction) (bool, error),
	stopAtFirstMatch bool,
) ([]*bitcoin.Transaction, error) {
	walletTransactions, err := btcChain.GetTransactionsForPublicKeyHash(
		lookupPublicKeyHash,
		transactionLimit,
	)
	if err != nil {
		return nil, fmt.Errorf(
			"failed to get transactions for wallet: [%v]",
			err,
		)
	}

	var unprovenTransactions []*bitcoin.Transaction

	for _, transaction := range walletTransactions {
		matched, err := isUnproven(transaction)
		if err != nil {
			return nil, fmt.Errorf(
				"failed to check if transaction is unproven: [%v]",
				err,
			)
		}

		if matched {
			unprovenTransactions = append(unprovenTransactions, transaction)
			if stopAtFirstMatch {
				break
			}
		}
	}

	return unprovenTransactions, nil
}

// spvProofAssembler is a type representing a function that is used
// to assemble an SPV proof for the given transaction hash and confirmations
// count.
type spvProofAssembler func(
	transactionHash bitcoin.Hash,
	requiredConfirmations uint,
	btcChain bitcoin.Chain,
) (*bitcoin.Transaction, *bitcoin.SpvProof, error)
