// Package spv implements the proof-maintenance half of the tBTC wallet-action
// domain. For each wallet action whose transaction has been executed on Bitcoin
// (deposit sweep, redemption, moving funds, moved funds sweep) it finds the
// unproven transactions and submits their SPV proofs to the host chain.
//
// Its counterpart is pkg/tbtcpg, the proposal-generation half, which decides
// which actions a wallet should take. The two packages deliberately mirror
// each other's file layout: a file here (deposit_sweep.go, redemptions.go,
// moving_funds.go, moved_funds_sweep.go) proves the transaction produced by
// the action whose proposal is generated by the same-named file there.
package spv

import (
	"bytes"
	"context"
	"encoding/hex"
	"fmt"
	"math/big"
	"time"

	"github.com/keep-network/keep-core/pkg/tbtc"

	"github.com/ipfs/go-log/v2"

	"github.com/keep-network/keep-core/pkg/bitcoin"
	"github.com/keep-network/keep-core/pkg/clientinfo"
	"github.com/keep-network/keep-core/pkg/maintainer/btcdiff"
)

var logger = log.Logger("keep-maintainer-spv")

// proofSkipReason explains why an SPV proof cannot be assembled for a
// transaction in the current cycle. It lets callers log and record metrics
// with the specific cause instead of collapsing every skip into one generic
// message.
type proofSkipReason int

const (
	// proofSkipNone means the proof is within the relay's difficulty range and
	// should be assembled once enough confirmations accumulate.
	proofSkipNone proofSkipReason = iota
	// proofSkipOutsideRelayRange means the decisive header matched neither the
	// current nor the previous relay epoch difficulty. The Bridge would revert
	// with "Not at current or previous difficulty". This is usually transient -
	// the transaction's epoch is not yet proven in the relay - and resolves as
	// the relay advances.
	proofSkipOutsideRelayRange
	// proofSkipExceededMaxHeaders means no decisive header was found and not
	// enough difficulty accumulated within the configured MaxProofHeaders
	// bound. Because the proof window is anchored at a fixed start block, a
	// run of leading minimum-difficulty (DIFF1) headers longer than the bound
	// is permanently unprovable rather than merely delayed, hence it is
	// signalled separately.
	proofSkipExceededMaxHeaders
)

// MetricsRecorder records proof counters and maintainer health gauges. It is
// satisfied by *clientinfo.PerformanceMetrics. A nil MetricsRecorder is a valid
// argument that disables metrics recording: callers must treat nil as "metrics
// off" and guard every invocation against it.
type MetricsRecorder interface {
	IncrementCounter(name string, value float64)
	SetGauge(name string, value float64)
}

func Initialize(
	ctx context.Context,
	config Config,
	spvChain Chain,
	btcDiffChain btcdiff.Chain,
	btcChain bitcoin.Chain,
	metricsRecorder MetricsRecorder,
) {
	spvMaintainer := &spvMaintainer{
		config:          config,
		spvChain:        spvChain,
		btcDiffChain:    btcDiffChain,
		btcChain:        btcChain,
		metricsRecorder: metricsRecorder,
	}

	if config.Reservations.LeaderDutiesEnabled {
		logger.Infof(
			"SPV maintainer reservation proof submission is enabled; " +
				"ensure the paired Tbtc.Reservations.LeaderDutiesEnabled flag is also " +
				"enabled in the client config for end-to-end operation",
		)
		// Reservation acceptance/re-anchor proofs run on a dedicated loop,
		// not through the generic proofTypes map: SubmitReservationProof
		// requires the (reservationKey, requestNonce) pair of the action
		// generation being proven, which the generic
		// unprovenTransactionsGetter/transactionProofSubmitter signatures
		// (shared by deposit sweep, redemption, moving funds, and moved
		// funds sweep, none of which need that pair) cannot carry. See
		// reservation_proof_loop.go.
		go maintainReservationProofs(ctx, config, spvChain, btcDiffChain, btcChain, metricsRecorder)

		// Reservation watcher wiring (stranding / stale-deposit /
		// action-timeout - see reservation_wiring.go) is a mandatory,
		// permissionless, network-wide duty, not a leader-election duty,
		// but it lives in this package and this is the process
		// guaranteed to run whenever the reservation feature is enabled
		// end-to-end. cmd/start.go's client process also wires the same
		// watchers against its own tbtcChain handle (see its call site
		// for why it is kept in addition to this one rather than instead
		// of it). walletClosedChain requires a type assertion because
		// spv.Chain does not declare OnWalletClosed; every production
		// Chain implementation (ethereum's tbtc.Chain) satisfies it.
		// This process has no visibility into the client's own
		// Tbtc.Reservations.LeaderDutiesEnabled flag, so it passes true
		// to skip WireReservationWatchers's paired-flag misconfiguration
		// self-check, relying on the informational log above instead.
		// The operator explicitly opted into reservation duties via this
		// flag, so a failure to wire the watchers is treated as fatal,
		// matching cmd/start.go's severity for the same failure.
		walletClosedChain, ok := spvChain.(WalletClosedChain)
		if !ok {
			logger.Fatalf(
				"cannot wire reservation watchers: chain implementation " +
					"does not support wallet closed event subscription",
			)
		}
		if err := WireReservationWatchers(ctx, walletClosedChain, spvChain, true); err != nil {
			logger.Fatalf("failed to wire reservation watchers: [%v]", err)
		}
	}

	go spvMaintainer.startControlLoop(ctx)
}

// proofTypes holds the information about proof types supported by the
// SPV maintainer.
var proofTypes = map[tbtc.WalletActionType]struct {
	unprovenTransactionsGetter unprovenTransactionsGetter
	transactionProofSubmitter  transactionProofSubmitter
}{
	tbtc.ActionDepositSweep: {
		unprovenTransactionsGetter: getUnprovenDepositSweepTransactions,
		transactionProofSubmitter:  SubmitDepositSweepProof,
	},
	tbtc.ActionRedemption: {
		unprovenTransactionsGetter: getUnprovenRedemptionTransactions,
		transactionProofSubmitter:  SubmitRedemptionProof,
	},
	tbtc.ActionMovingFunds: {
		unprovenTransactionsGetter: getUnprovenMovingFundsTransactions,
		transactionProofSubmitter:  SubmitMovingFundsProof,
	},
	tbtc.ActionMovedFundsSweep: {
		unprovenTransactionsGetter: getUnprovenMovedFundsSweepTransactions,
		transactionProofSubmitter:  SubmitMovedFundsSweepProof,
	},
}

type spvMaintainer struct {
	config          Config
	spvChain        Chain
	btcDiffChain    btcdiff.Chain
	btcChain        bitcoin.Chain
	metricsRecorder MetricsRecorder
}

func (sm *spvMaintainer) startControlLoop(ctx context.Context) {
	logger.Info("starting SPV maintainer")
	sm.setHealthGauge(clientinfo.MetricSpvMaintainerActive, 1)
	sm.recordActivity()
	maxBackoff := sm.config.RestartBackoffTime
	if sm.config.IdleBackoffTime > maxBackoff {
		maxBackoff = sm.config.IdleBackoffTime
	}
	sm.setHealthGauge(clientinfo.MetricSpvMaintainerMaxBackoffSeconds, maxBackoff.Seconds())

	defer func() {
		sm.setHealthGauge(clientinfo.MetricSpvMaintainerActive, 0)
		logger.Info("stopping SPV maintainer")
	}()

	for {
		err := sm.maintainSpv(ctx)
		if ctx.Err() != nil {
			return
		}
		if err != nil {
			logger.Errorf(
				"error while maintaining SPV: [%v]; restarting maintainer",
				err,
			)
		}

		select {
		case <-time.After(sm.config.RestartBackoffTime):
		case <-ctx.Done():
			return
		}
	}
}

func (sm *spvMaintainer) maintainSpv(ctx context.Context) error {
	for {
		for action, v := range proofTypes {
			if err := ctx.Err(); err != nil {
				return err
			}
			logger.Infof("starting [%s] proof task execution...", action)

			if err := sm.runProofTask(
				action,
				v.unprovenTransactionsGetter,
				v.transactionProofSubmitter,
			); err != nil {
				return fmt.Errorf(
					"error while proving [%s] transactions: [%v]",
					action,
					err,
				)
			}

			logger.Infof("[%s] proof task completed", action)
		}

		sm.setHealthGauge(clientinfo.MetricSpvMaintainerLastSuccessTimestamp, float64(time.Now().Unix()))

		logger.Infof(
			"proof tasks completed; next run in [%s]",
			sm.config.IdleBackoffTime,
		)

		select {
		case <-time.After(sm.config.IdleBackoffTime):
		case <-ctx.Done():
			return ctx.Err()
		}
	}
}

// unprovenTransactionsGetter is a type representing a function that is
// used to get unproven Bitcoin transactions.
type unprovenTransactionsGetter func(
	historyDepth uint64,
	transactionLimit int,
	btcChain bitcoin.Chain,
	spvChain Chain,
) (
	[]*bitcoin.Transaction,
	error,
)

// transactionProofSubmitter is a type representing a function that is used
// to submit the constructed SPV proof to the host chain.
type transactionProofSubmitter func(
	transactionHash bitcoin.Hash,
	requiredConfirmations uint,
	btcChain bitcoin.Chain,
	spvChain Chain,
	metricsRecorder MetricsRecorder,
) error

// proveTransactions gets unproven Bitcoin transactions using the provided
// unprovenTransactionsGetter, build the SPV proofs, and submits them using
// the provided transactionProofSubmitter.
func (sm *spvMaintainer) proveTransactions(
	unprovenTransactionsGetter unprovenTransactionsGetter,
	transactionProofSubmitter transactionProofSubmitter,
) error {
	transactions, err := unprovenTransactionsGetter(
		sm.config.HistoryDepth,
		sm.config.TransactionLimit,
		sm.btcChain,
		sm.spvChain,
	)
	if err != nil {
		return fmt.Errorf("failed to get unproven transactions: [%v]", err)
	}

	logger.Infof("found [%d] unproven transaction(s)", len(transactions))

	// One cache per pass, shared by every transaction's getProofInfo call
	// below; see proofInfoCache.
	cache := newProofInfoCache()

	for _, transaction := range transactions {
		// Print the transaction in the same endianness as block explorers do.
		transactionHashStr := transaction.Hash().Hex(bitcoin.ReversedByteOrder)

		logger.Infof(
			"proceeding with proof for transaction [%s]",
			transactionHashStr,
		)

		accumulatedConfirmations, requiredConfirmations, skipReason, err := getProofInfo(
			transaction.Hash(),
			sm.btcChain,
			sm.spvChain,
			sm.btcDiffChain,
			sm.config.MaxProofHeaders,
			cache,
		)
		if err != nil {
			return fmt.Errorf("failed to get proof info: [%v]", err)
		}

		switch skipReason {
		case proofSkipOutsideRelayRange:
			// The required proof goes outside the previous and current
			// difficulty epochs as seen by the relay. Skip the transaction. It
			// will most likely be proven later, once the relay advances.
			logger.Warnf(
				"skipped proving transaction [%s]; the range "+
					"of the required proof goes outside the previous and "+
					"current difficulty epochs as seen by the relay",
				transactionHashStr,
			)
			if recorder := sm.metricsRecorder; recorder != nil {
				recorder.IncrementCounter(
					clientinfo.MetricSpvProofSkippedOutsideRelayRangeTotal,
					1,
				)
			}
			continue
		case proofSkipExceededMaxHeaders:
			// No decisive header was found and not enough difficulty
			// accumulated within the configured MaxProofHeaders bound. Unlike
			// the range skip above, this transaction may be permanently
			// unprovable if it is buried under a run of minimum-difficulty
			// blocks longer than the bound.
			logger.Errorf(
				"skipped proving transaction [%s]; could not find a decisive "+
					"header or accumulate enough difficulty within [%d] "+
					"headers; the transaction may be permanently unprovable",
				transactionHashStr,
				sm.config.MaxProofHeaders,
			)
			if recorder := sm.metricsRecorder; recorder != nil {
				recorder.IncrementCounter(
					clientinfo.MetricSpvProofSkippedExceededMaxHeadersTotal,
					1,
				)
			}
			continue
		case proofSkipNone:
			// The proof is within range and assemblable; proceed to the
			// confirmation check and submission below.
		default:
			// Defensive: a skip reason getProofInfo does not currently emit
			// must never silently fall through to proof submission.
			return fmt.Errorf(
				"unexpected proof skip reason [%d] for transaction [%s]",
				skipReason,
				transactionHashStr,
			)
		}

		if accumulatedConfirmations < requiredConfirmations {
			// Skip the transaction as it has not accumulated enough
			// confirmations. It will be proven later.
			logger.Infof(
				"skipped proving transaction [%s]; transaction "+
					"has [%v/%v] confirmations",
				transactionHashStr,
				accumulatedConfirmations,
				requiredConfirmations,
			)
			continue
		}

		err = transactionProofSubmitter(
			transaction.Hash(),
			requiredConfirmations,
			sm.btcChain,
			sm.spvChain,
			sm.metricsRecorder,
		)
		if err != nil {
			return err
		}

		logger.Infof(
			"successfully submitted proof for transaction [%s]",
			transactionHashStr,
		)
	}

	logger.Infof("finished round of proving transactions")

	return nil
}

func isInputCurrentWalletsMainUTXO(
	fundingTxHash bitcoin.Hash,
	fundingOutputIndex uint32,
	walletPublicKeyHash [20]byte,
	btcChain bitcoin.Chain,
	spvChain Chain,
) (bool, error) {
	// Get the transaction the input originated from to calculate the input value.
	previousTransaction, err := btcChain.GetTransaction(fundingTxHash)
	if err != nil {
		return false, fmt.Errorf("failed to get previous transaction: [%v]", err)
	}
	if fundingOutputIndex >= uint32(len(previousTransaction.Outputs)) {
		return false, fmt.Errorf(
			"funding output index [%d] out of range for transaction [%s] "+
				"with [%d] outputs",
			fundingOutputIndex,
			fundingTxHash.String(),
			len(previousTransaction.Outputs),
		)
	}
	fundingOutputValue := previousTransaction.Outputs[fundingOutputIndex].Value

	// Assume the input is the main UTXO and calculate hash.
	mainUtxoHash := spvChain.ComputeMainUtxoHash(&bitcoin.UnspentTransactionOutput{
		Outpoint: &bitcoin.TransactionOutpoint{
			TransactionHash: fundingTxHash,
			OutputIndex:     fundingOutputIndex,
		},
		Value: fundingOutputValue,
	})

	// Get the wallet and check if its main UTXO matches the calculated hash.
	wallet, err := spvChain.GetWallet(walletPublicKeyHash)
	if err != nil {
		return false, fmt.Errorf("failed to get wallet: [%v]", err)
	}

	return bytes.Equal(mainUtxoHash[:], wallet.MainUtxoHash[:]), nil
}

// proofInfoCache holds proof-invariant data - the SPV proof difficulty
// factor and the relay's current/previous epoch difficulties - loaded once
// per proof-loop pass and shared by getProofInfo across every candidate
// transaction proved in that pass, together with a pass-local cache of
// already-fetched Bitcoin block headers keyed by height. A transaction's
// proof walk is still bounded by its own maxProofHeaders argument; only the
// underlying chain reads are memoized and shared, never the per-transaction
// walk logic itself.
//
// The Bitcoin chain tip is deliberately excluded from that once-per-pass
// caching. txProofDifficultyFactor and the epoch difficulties are
// governance-parameter-like values that cannot change within a single
// pass's timeframe, but the tip advances whenever a real Bitcoin block is
// mined - which can happen partway through a pass that proves many
// transactions. Deriving a transaction's proof start block from a tip
// cached at pass start while its confirmation count is read fresh would mix
// two different observation windows and mis-locate the proof, so the tip is
// re-fetched on every call via currentBlockHeight instead; see its doc
// comment.
//
// Both getProofInfo callers - spvMaintainer.proveTransactions and the
// reservation proof loop's proveReservationAcceptanceActions /
// proveReservationReanchorActions - create one proofInfoCache per pass and
// thread it through every getProofInfo call in that pass.
//
// A proofInfoCache is not safe for concurrent use: callers create one per
// pass and drive it from a single goroutine.
type proofInfoCache struct {
	loaded                  bool
	txProofDifficultyFactor *big.Int
	currentEpochDifficulty  *big.Int
	previousEpochDifficulty *big.Int

	headers map[uint64]*bitcoin.BlockHeader
}

// newProofInfoCache creates an empty proofInfoCache for one proof-loop pass.
func newProofInfoCache() *proofInfoCache {
	return &proofInfoCache{headers: make(map[uint64]*bitcoin.BlockHeader)}
}

// load populates the proof-invariant chain reads - the SPV proof difficulty
// factor and the relay's current/previous epoch difficulties - on first use
// and is a no-op on every subsequent call for the lifetime of the cache.
// The Bitcoin chain tip is not among them; it is re-fetched on every call by
// currentBlockHeight instead. See proofInfoCache for why.
func (c *proofInfoCache) load(
	spvChain Chain,
	btcDiffChain btcdiff.Chain,
) error {
	if c.loaded {
		return nil
	}

	txProofDifficultyFactor, err := spvChain.TxProofDifficultyFactor()
	if err != nil {
		return fmt.Errorf(
			"failed to get transaction proof difficulty factor: [%v]",
			err,
		)
	}

	currentEpochDifficulty, previousEpochDifficulty, err :=
		btcDiffChain.GetCurrentAndPrevEpochDifficulty()
	if err != nil {
		return fmt.Errorf(
			"failed to get Bitcoin epoch difficulties: [%v]",
			err,
		)
	}

	c.txProofDifficultyFactor = txProofDifficultyFactor
	c.currentEpochDifficulty = currentEpochDifficulty
	c.previousEpochDifficulty = previousEpochDifficulty
	c.loaded = true

	return nil
}

// currentBlockHeight returns the current Bitcoin chain tip. Unlike every
// other value on proofInfoCache, the tip is never cached for the lifetime of
// a pass: a real Bitcoin block can be mined between two getProofInfo calls
// in the same pass, and pairing a stale tip with a freshly-read transaction
// confirmation count would derive the wrong proof start block.
// currentBlockHeight is therefore re-fetched on every call.
func (c *proofInfoCache) currentBlockHeight(
	btcChain bitcoin.Chain,
) (uint, error) {
	latestBlockHeight, err := btcChain.GetLatestBlockHeight()
	if err != nil {
		return 0, fmt.Errorf("failed to get latest block height: [%v]", err)
	}

	return latestBlockHeight, nil
}

// blockHeader returns the block header at height, fetching and caching it on
// first request and returning the cached header on every subsequent request
// for the same height within the same pass.
func (c *proofInfoCache) blockHeader(
	btcChain bitcoin.Chain,
	height uint64,
) (*bitcoin.BlockHeader, error) {
	if header, ok := c.headers[height]; ok {
		return header, nil
	}

	header, err := btcChain.GetBlockHeader(uint(height))
	if err != nil {
		return nil, err
	}

	c.headers[height] = header

	return header, nil
}

// getProofInfo returns information about the SPV proof: the accumulated number
// of confirmations, the required number of confirmations, and a proofSkipReason
// indicating whether the proof can be assembled (proofSkipNone) or why it must
// be skipped this cycle. The confirmation counts are meaningful only when the
// reason is proofSkipNone.
//
// maxProofHeaders == 0 is normalized to DefaultMaxProofHeaders here - the
// single place both the generic SPV loop and the reservation proof loop
// funnel through - so a Config built programmatically without going through
// flag registration (which applies the 144 default; see cmd/flags.go)
// behaves identically to one that was.
//
// cache holds the pass-invariant proof difficulty factor, epoch
// difficulties, and already-fetched block headers, plus the Bitcoin chain
// tip re-fetched fresh on every call; see proofInfoCache.
func getProofInfo(
	transactionHash bitcoin.Hash,
	btcChain bitcoin.Chain,
	spvChain Chain,
	btcDiffChain btcdiff.Chain,
	maxProofHeaders uint,
	cache *proofInfoCache,
) (
	uint, uint, proofSkipReason, error,
) {
	if maxProofHeaders == 0 {
		maxProofHeaders = DefaultMaxProofHeaders
	}

	if err := cache.load(spvChain, btcDiffChain); err != nil {
		return 0, 0, proofSkipNone, err
	}
	latestBlockHeight, err := cache.currentBlockHeight(btcChain)
	if err != nil {
		return 0, 0, proofSkipNone, err
	}
	txProofDifficultyFactor := cache.txProofDifficultyFactor
	currentEpochDifficulty := cache.currentEpochDifficulty
	previousEpochDifficulty := cache.previousEpochDifficulty

	accumulatedConfirmations, err := btcChain.GetTransactionConfirmations(
		context.Background(),
		transactionHash,
	)
	if err != nil {
		return 0, 0, proofSkipNone, fmt.Errorf(
			"failed to get transaction confirmations: [%v]",
			err,
		)
	}

	// Calculate the starting block of the proof.
	proofStartBlock := uint64(latestBlockHeight - accumulatedConfirmations + 1)

	// Walk the header chain forward, mirroring the Bridge's
	// BitcoinTx.determineRequestedDifficulty and evaluateProofDifficulty
	// behavior:
	// - minimum-difficulty (DIFF1) headers are skipped while looking for the
	//   decisive header, but only when both relay epoch difficulties are
	//   above minimum (testnet4 BIP94 blocks in real epochs),
	// - the first decisive header must match the relay's current or previous
	//   epoch difficulty; that value becomes the requested difficulty,
	// - headers are accumulated until their total observed difficulty reaches
	//   requested difficulty times the transaction proof difficulty factor.
	one := big.NewInt(1)
	skipMinDifficulty := currentEpochDifficulty.Cmp(one) > 0 &&
		previousEpochDifficulty.Cmp(one) > 0

	var requestedDiff *big.Int
	var totalDifficultyRequired *big.Int
	observedDiff := big.NewInt(0)
	headerCount := uint(0)

	for {
		if headerCount >= maxProofHeaders {
			// Could not find a decisive header or accumulate enough
			// difficulty within the header bound. Signal the distinct cause;
			// with a fixed proof window this may be permanent rather than
			// merely delayed.
			return 0, 0, proofSkipExceededMaxHeaders, nil
		}

		blockHeight := proofStartBlock + uint64(headerCount)
		if blockHeight > uint64(latestBlockHeight) {
			// Not enough mined blocks yet to assemble the proof. Report the
			// number of headers needed so far plus one more; the caller will
			// see accumulated < required and skip the transaction for now.
			return accumulatedConfirmations, headerCount + 1, proofSkipNone, nil
		}

		header, err := cache.blockHeader(btcChain, blockHeight)
		if err != nil {
			return 0, 0, proofSkipNone, fmt.Errorf(
				"failed to get block header at height [%v]: [%v]",
				blockHeight,
				err,
			)
		}

		headerDiff := header.Difficulty()
		headerCount++
		observedDiff.Add(observedDiff, headerDiff)

		if requestedDiff == nil {
			// Still looking for the decisive header. Skip minimum-difficulty
			// (DIFF1) headers by exact target equality, mirroring the Bridge's
			// target == MIN_DIFFICULTY_TARGET predicate. Their work is still
			// added to observedDiff above.
			if skipMinDifficulty &&
				header.Target().Cmp(btcdiff.LightRelayMinDifficultyTarget) == 0 {
				continue
			}

			if headerDiff.Cmp(currentEpochDifficulty) == 0 {
				requestedDiff = currentEpochDifficulty
			} else if headerDiff.Cmp(previousEpochDifficulty) == 0 {
				requestedDiff = previousEpochDifficulty
			} else {
				// The Bridge would revert with "Not at current or previous
				// difficulty". The transaction is either too fresh (its epoch
				// is not yet proven in the relay) or too old. Skip it; it may
				// be proven in the future.
				return 0, 0, proofSkipOutsideRelayRange, nil
			}

			totalDifficultyRequired = new(big.Int).Mul(
				requestedDiff,
				txProofDifficultyFactor,
			)
		}

		if observedDiff.Cmp(totalDifficultyRequired) >= 0 {
			return accumulatedConfirmations, headerCount, proofSkipNone, nil
		}
	}
}

// walletEvent is a type constraint representing wallet-related chain events.
type walletEvent interface {
	GetWalletPublicKeyHash() [20]byte
}

// uniqueWalletPublicKeyHashes parses the list of wallet-related events and
// returns a list of unique wallet public key hashes.
func uniqueWalletPublicKeyHashes[T walletEvent](events []T) [][20]byte {
	cache := make(map[string]struct{})
	var publicKeyHashes [][20]byte

	for _, event := range events {
		key := event.GetWalletPublicKeyHash()
		strKey := hex.EncodeToString(key[:])

		// Check for uniqueness
		if _, exists := cache[strKey]; !exists {
			cache[strKey] = struct{}{}
			publicKeyHashes = append(publicKeyHashes, key)
		}
	}

	return publicKeyHashes
}

// unprovenSearchStartBlock returns the starting block of the range in which
// the events used to find unproven transactions are searched for. It is
// derived from the current chain tip and the configured history depth.
func unprovenSearchStartBlock(
	historyDepth uint64,
	spvChain Chain,
) (uint64, error) {
	blockCounter, err := spvChain.BlockCounter()
	if err != nil {
		return 0, fmt.Errorf("failed to get block counter: [%v]", err)
	}

	currentBlock, err := blockCounter.CurrentBlock()
	if err != nil {
		return 0, fmt.Errorf("failed to get current block: [%v]", err)
	}

	// Guard against unsigned underflow on short chains (e.g. early test
	// networks) where the configured history depth can exceed the current
	// tip; clamp the search start to the genesis block instead of wrapping
	// around to a near-maximum block number.
	if historyDepth > currentBlock {
		return 0, nil
	}

	return currentBlock - historyDepth, nil
}

// collectUnprovenWalletTransactions returns the recent transactions of the
// wallet identified by lookupPublicKeyHash that satisfy the isUnproven
// predicate. When stopAtFirstMatch is true it returns as soon as the first
// matching transaction is found, which is sufficient for wallet operations
// that can have at most one unproven transaction at a time.
func collectUnprovenWalletTransactions(
	lookupPublicKeyHash [20]byte,
	transactionLimit int,
	btcChain bitcoin.Chain,
	isUnproven func(transaction *bitcoin.Transaction) (bool, error),
	stopAtFirstMatch bool,
) ([]*bitcoin.Transaction, error) {
	walletTransactions, err := btcChain.GetTransactionsForPublicKeyHash(
		lookupPublicKeyHash,
		transactionLimit,
	)
	if err != nil {
		return nil, fmt.Errorf(
			"failed to get transactions for wallet: [%v]",
			err,
		)
	}

	var unprovenTransactions []*bitcoin.Transaction

	for _, transaction := range walletTransactions {
		matched, err := isUnproven(transaction)
		if err != nil {
			return nil, fmt.Errorf(
				"failed to check if transaction is unproven: [%v]",
				err,
			)
		}

		if matched {
			unprovenTransactions = append(unprovenTransactions, transaction)
			if stopAtFirstMatch {
				break
			}
		}
	}

	return unprovenTransactions, nil
}

// spvProofAssembler is a type representing a function that is used
// to assemble an SPV proof for the given transaction hash and confirmations
// count.
type spvProofAssembler func(
	transactionHash bitcoin.Hash,
	requiredConfirmations uint,
	btcChain bitcoin.Chain,
) (*bitcoin.Transaction, *bitcoin.SpvProof, error)
