// Package spv implements the proof-maintenance half of the tBTC wallet-action
// domain. For each wallet action whose transaction has been executed on Bitcoin
// (deposit sweep, redemption, moving funds, moved funds sweep) it finds the
// unproven transactions and submits their SPV proofs to the host chain.
//
// Its counterpart is pkg/tbtcpg, the proposal-generation half, which decides
// which actions a wallet should take. The two packages deliberately mirror
// each other's file layout: a file here (deposit_sweep.go, redemptions.go,
// moving_funds.go, moved_funds_sweep.go) proves the transaction produced by
// the action whose proposal is generated by the same-named file there.
package spv

import (
	"bytes"
	"context"
	"encoding/hex"
	"fmt"
	"math/big"
	"sync"
	"time"

	"github.com/keep-network/keep-core/pkg/tbtc"

	"github.com/btcsuite/btcd/blockchain"
	"github.com/ipfs/go-log/v2"

	"github.com/keep-network/keep-core/pkg/bitcoin"
	"github.com/keep-network/keep-core/pkg/maintainer/btcdiff"
)

var logger = log.Logger("keep-maintainer-spv")

// The maximum number of block headers allowed in a single SPV proof. Bounds
// the forward walk over headers when computing required confirmations
// (relevant on testnet4 where long runs of minimum-difficulty blocks occur).
//
// 144 is one day's worth of blocks at Bitcoin's ~10-minute target spacing. In a
// normal epoch every header contributes the full epoch difficulty, so a proof
// needs only a handful of headers (txProofDifficultyFactor headers, typically
// 6); the bound leaves ample margin. It exists solely to cap the walk against a
// pathological run of leading minimum-difficulty (DIFF1) headers. Note the
// proof window is anchored at a fixed start block and does not slide, so a run
// of leading DIFF1 headers longer than this bound makes the transaction
// permanently unprovable rather than merely delayed (see proofSkipReason).
const maxProofHeaders = 144

// minDifficultyTarget is the Bitcoin minimum-difficulty target, decoded from
// compact bits 0x1d00ffff. It mirrors the Bridge's
// BitcoinTx.MIN_DIFFICULTY_TARGET and is used to detect testnet4 BIP94
// minimum-difficulty (DIFF1) headers by exact target equality, matching the
// on-chain skip predicate.
var minDifficultyTarget = blockchain.CompactToBig(0x1d00ffff)

// proofSkipReason explains why an SPV proof cannot be assembled for a
// transaction in the current cycle. It lets callers log and record metrics with
// the specific cause instead of collapsing every skip into one generic message.
type proofSkipReason int

const (
	// proofSkipNone means the proof is within the relay's difficulty range and
	// should be assembled once enough confirmations accumulate.
	proofSkipNone proofSkipReason = iota
	// proofSkipOutsideRelayRange means the decisive header matched neither the
	// current nor the previous relay epoch difficulty. The Bridge would revert
	// with "Not at current or previous difficulty". This is usually transient -
	// the transaction's epoch is not yet proven in the relay - and resolves as
	// the relay advances.
	proofSkipOutsideRelayRange
	// proofSkipExceededMaxHeaders means no decisive header was found and not
	// enough difficulty accumulated within maxProofHeaders. Because the proof
	// window is anchored at a fixed start block, a run of leading
	// minimum-difficulty (DIFF1) headers longer than the bound is permanently
	// unprovable rather than merely delayed, hence it is signalled separately.
	proofSkipExceededMaxHeaders
)

func Initialize(
	ctx context.Context,
	config Config,
	spvChain Chain,
	btcDiffChain btcdiff.Chain,
	btcChain bitcoin.Chain,
) {
	spvMaintainer := &spvMaintainer{
		config:       config,
		spvChain:     spvChain,
		btcDiffChain: btcDiffChain,
		btcChain:     btcChain,
	}

	go spvMaintainer.startControlLoop(ctx)
}

// globalMetricsRecorder is a package-level variable to access metrics recorder
// from proof submission functions.
var (
	globalMetricsRecorderMu sync.RWMutex
	globalMetricsRecorder   interface {
		IncrementCounter(name string, value float64)
	}
)

// SetMetricsRecorder sets the metrics recorder for the SPV maintainer.
// This allows recording metrics for proof submissions.
func SetMetricsRecorder(recorder interface {
	IncrementCounter(name string, value float64)
}) {
	globalMetricsRecorderMu.Lock()
	defer globalMetricsRecorderMu.Unlock()
	globalMetricsRecorder = recorder
}

// getMetricsRecorder safely retrieves the metrics recorder.
func getMetricsRecorder() interface {
	IncrementCounter(name string, value float64)
} {
	globalMetricsRecorderMu.RLock()
	defer globalMetricsRecorderMu.RUnlock()
	return globalMetricsRecorder
}

// proofTypes holds the information about proof types supported by the
// SPV maintainer.
var proofTypes = map[tbtc.WalletActionType]struct {
	unprovenTransactionsGetter unprovenTransactionsGetter
	transactionProofSubmitter  transactionProofSubmitter
}{
	tbtc.ActionDepositSweep: {
		unprovenTransactionsGetter: getUnprovenDepositSweepTransactions,
		transactionProofSubmitter:  SubmitDepositSweepProof,
	},
	tbtc.ActionRedemption: {
		unprovenTransactionsGetter: getUnprovenRedemptionTransactions,
		transactionProofSubmitter:  SubmitRedemptionProof,
	},
	tbtc.ActionMovingFunds: {
		unprovenTransactionsGetter: getUnprovenMovingFundsTransactions,
		transactionProofSubmitter:  SubmitMovingFundsProof,
	},
	tbtc.ActionMovedFundsSweep: {
		unprovenTransactionsGetter: getUnprovenMovedFundsSweepTransactions,
		transactionProofSubmitter:  SubmitMovedFundsSweepProof,
	},
}

type spvMaintainer struct {
	config       Config
	spvChain     Chain
	btcDiffChain btcdiff.Chain
	btcChain     bitcoin.Chain
}

func (sm *spvMaintainer) startControlLoop(ctx context.Context) {
	logger.Info("starting SPV maintainer")

	defer func() {
		logger.Info("stopping SPV maintainer")
	}()

	for {
		err := sm.maintainSpv(ctx)
		if err != nil {
			logger.Errorf(
				"error while maintaining SPV: [%v]; restarting maintainer",
				err,
			)
		}

		select {
		case <-time.After(sm.config.RestartBackoffTime):
		case <-ctx.Done():
			return
		}
	}
}

func (sm *spvMaintainer) maintainSpv(ctx context.Context) error {
	for {
		for action, v := range proofTypes {
			logger.Infof("starting [%s] proof task execution...", action)

			if err := sm.proveTransactions(
				v.unprovenTransactionsGetter,
				v.transactionProofSubmitter,
			); err != nil {
				return fmt.Errorf(
					"error while proving [%s] transactions: [%v]",
					action,
					err,
				)
			}

			logger.Infof("[%s] proof task completed", action)
		}

		logger.Infof(
			"proof tasks completed; next run in [%s]",
			sm.config.IdleBackoffTime,
		)

		select {
		case <-time.After(sm.config.IdleBackoffTime):
		case <-ctx.Done():
			return ctx.Err()
		}
	}
}

// unprovenTransactionsGetter is a type representing a function that is
// used to get unproven Bitcoin transactions.
type unprovenTransactionsGetter func(
	historyDepth uint64,
	transactionLimit int,
	btcChain bitcoin.Chain,
	spvChain Chain,
) (
	[]*bitcoin.Transaction,
	error,
)

// transactionProofSubmitter is a type representing a function that is used
// to submit the constructed SPV proof to the host chain.
type transactionProofSubmitter func(
	transactionHash bitcoin.Hash,
	requiredConfirmations uint,
	btcChain bitcoin.Chain,
	spvChain Chain,
) error

// proveTransactions gets unproven Bitcoin transactions using the provided
// unprovenTransactionsGetter, build the SPV proofs, and submits them using
// the provided transactionProofSubmitter.
func (sm *spvMaintainer) proveTransactions(
	unprovenTransactionsGetter unprovenTransactionsGetter,
	transactionProofSubmitter transactionProofSubmitter,
) error {
	transactions, err := unprovenTransactionsGetter(
		sm.config.HistoryDepth,
		sm.config.TransactionLimit,
		sm.btcChain,
		sm.spvChain,
	)
	if err != nil {
		return fmt.Errorf("failed to get unproven transactions: [%v]", err)
	}

	logger.Infof("found [%d] unproven transaction(s)", len(transactions))

	for _, transaction := range transactions {
		// Print the transaction in the same endianness as block explorers do.
		transactionHashStr := transaction.Hash().Hex(bitcoin.ReversedByteOrder)

		logger.Infof(
			"proceeding with proof for transaction [%s]",
			transactionHashStr,
		)

		accumulatedConfirmations, requiredConfirmations, skipReason, err := getProofInfo(
			transaction.Hash(),
			sm.btcChain,
			sm.spvChain,
			sm.btcDiffChain,
		)
		if err != nil {
			return fmt.Errorf("failed to get proof info: [%v]", err)
		}

		switch skipReason {
		case proofSkipOutsideRelayRange:
			// The required proof goes outside the previous and current
			// difficulty epochs as seen by the relay. Skip the transaction. It
			// will most likely be proven later, once the relay advances.
			logger.Warnf(
				"skipped proving transaction [%s]; the range "+
					"of the required proof goes outside the previous and "+
					"current difficulty epochs as seen by the relay",
				transactionHashStr,
			)
			if recorder := getMetricsRecorder(); recorder != nil {
				recorder.IncrementCounter(
					"spv_proof_skipped_outside_relay_range_total",
					1,
				)
			}
			continue
		case proofSkipExceededMaxHeaders:
			// No decisive header was found and not enough difficulty
			// accumulated within maxProofHeaders. Unlike the range skip above,
			// this transaction may be permanently unprovable if it is buried
			// under a run of minimum-difficulty blocks longer than the bound.
			logger.Errorf(
				"skipped proving transaction [%s]; could not find a decisive "+
					"header or accumulate enough difficulty within [%d] "+
					"headers; the transaction may be permanently unprovable",
				transactionHashStr,
				maxProofHeaders,
			)
			if recorder := getMetricsRecorder(); recorder != nil {
				recorder.IncrementCounter(
					"spv_proof_skipped_exceeded_max_headers_total",
					1,
				)
			}
			continue
		case proofSkipNone:
			// The proof is within range and assemblable; proceed to the
			// confirmation check and submission below.
		default:
			// Defensive: a skip reason getProofInfo does not currently emit
			// must never silently fall through to proof submission.
			return fmt.Errorf(
				"unexpected proof skip reason [%d] for transaction [%s]",
				skipReason,
				transactionHashStr,
			)
		}

		if accumulatedConfirmations < requiredConfirmations {
			// Skip the transaction as it has not accumulated enough
			// confirmations. It will be proven later.
			logger.Infof(
				"skipped proving transaction [%s]; transaction "+
					"has [%v/%v] confirmations",
				transactionHashStr,
				accumulatedConfirmations,
				requiredConfirmations,
			)
			continue
		}

		err = transactionProofSubmitter(
			transaction.Hash(),
			requiredConfirmations,
			sm.btcChain,
			sm.spvChain,
		)
		if err != nil {
			return err
		}

		logger.Infof(
			"successfully submitted proof for transaction [%s]",
			transactionHashStr,
		)
	}

	logger.Infof("finished round of proving transactions")

	return nil
}

func isInputCurrentWalletsMainUTXO(
	fundingTxHash bitcoin.Hash,
	fundingOutputIndex uint32,
	walletPublicKeyHash [20]byte,
	btcChain bitcoin.Chain,
	spvChain Chain,
) (bool, error) {
	// Get the transaction the input originated from to calculate the input value.
	previousTransaction, err := btcChain.GetTransaction(fundingTxHash)
	if err != nil {
		return false, fmt.Errorf("failed to get previous transaction: [%v]", err)
	}
	if fundingOutputIndex >= uint32(len(previousTransaction.Outputs)) {
		return false, fmt.Errorf(
			"funding output index [%d] out of range for transaction [%s] "+
				"with [%d] outputs",
			fundingOutputIndex,
			fundingTxHash.String(),
			len(previousTransaction.Outputs),
		)
	}
	fundingOutputValue := previousTransaction.Outputs[fundingOutputIndex].Value

	// Assume the input is the main UTXO and calculate hash.
	mainUtxoHash := spvChain.ComputeMainUtxoHash(&bitcoin.UnspentTransactionOutput{
		Outpoint: &bitcoin.TransactionOutpoint{
			TransactionHash: fundingTxHash,
			OutputIndex:     fundingOutputIndex,
		},
		Value: fundingOutputValue,
	})

	// Get the wallet and check if its main UTXO matches the calculated hash.
	wallet, err := spvChain.GetWallet(walletPublicKeyHash)
	if err != nil {
		return false, fmt.Errorf("failed to get wallet: [%v]", err)
	}

	return bytes.Equal(mainUtxoHash[:], wallet.MainUtxoHash[:]), nil
}

// getProofInfo returns information about the SPV proof: the accumulated number
// of confirmations, the required number of confirmations, and a proofSkipReason
// indicating whether the proof can be assembled (proofSkipNone) or why it must
// be skipped this cycle. The confirmation counts are meaningful only when the
// reason is proofSkipNone.
func getProofInfo(
	transactionHash bitcoin.Hash,
	btcChain bitcoin.Chain,
	spvChain Chain,
	btcDiffChain btcdiff.Chain,
) (
	uint, uint, proofSkipReason, error,
) {
	latestBlockHeight, err := btcChain.GetLatestBlockHeight()
	if err != nil {
		return 0, 0, proofSkipNone, fmt.Errorf(
			"failed to get latest block height: [%v]",
			err,
		)
	}

	accumulatedConfirmations, err := btcChain.GetTransactionConfirmations(
		context.Background(),
		transactionHash,
	)
	if err != nil {
		return 0, 0, proofSkipNone, fmt.Errorf(
			"failed to get transaction confirmations: [%v]",
			err,
		)
	}

	txProofDifficultyFactor, err := spvChain.TxProofDifficultyFactor()
	if err != nil {
		return 0, 0, proofSkipNone, fmt.Errorf(
			"failed to get transaction proof difficulty factor: [%v]",
			err,
		)
	}

	currentEpochDifficulty, previousEpochDifficulty, err :=
		btcDiffChain.GetCurrentAndPrevEpochDifficulty()
	if err != nil {
		return 0, 0, proofSkipNone, fmt.Errorf(
			"failed to get Bitcoin epoch difficulties: [%v]",
			err,
		)
	}

	// Calculate the starting block of the proof.
	proofStartBlock := uint64(latestBlockHeight - accumulatedConfirmations + 1)

	// Walk the header chain forward, mirroring the Bridge's
	// BitcoinTx.determineRequestedDifficulty and evaluateProofDifficulty
	// behavior:
	// - minimum-difficulty (DIFF1) headers are skipped while looking for the
	//   decisive header, but only when both relay epoch difficulties are
	//   above minimum (testnet4 BIP94 blocks in real epochs),
	// - the first decisive header must match the relay's current or previous
	//   epoch difficulty; that value becomes the requested difficulty,
	// - headers are accumulated until their total observed difficulty reaches
	//   requested difficulty times the transaction proof difficulty factor.
	one := big.NewInt(1)
	skipMinDifficulty := currentEpochDifficulty.Cmp(one) > 0 &&
		previousEpochDifficulty.Cmp(one) > 0

	var requestedDiff *big.Int
	var totalDifficultyRequired *big.Int
	observedDiff := big.NewInt(0)
	headerCount := uint(0)

	for {
		if headerCount >= maxProofHeaders {
			// Could not find a decisive header or accumulate enough
			// difficulty within the header bound. Signal the distinct cause;
			// with a fixed proof window this may be permanent rather than
			// merely delayed.
			return 0, 0, proofSkipExceededMaxHeaders, nil
		}

		blockHeight := proofStartBlock + uint64(headerCount)
		if blockHeight > uint64(latestBlockHeight) {
			// Not enough mined blocks yet to assemble the proof. Report the
			// number of headers needed so far plus one more; the caller will
			// see accumulated < required and skip the transaction for now.
			return accumulatedConfirmations, headerCount + 1, proofSkipNone, nil
		}

		header, err := btcChain.GetBlockHeader(uint(blockHeight))
		if err != nil {
			return 0, 0, proofSkipNone, fmt.Errorf(
				"failed to get block header at height [%v]: [%v]",
				blockHeight,
				err,
			)
		}

		headerDiff := header.Difficulty()
		headerCount++
		observedDiff.Add(observedDiff, headerDiff)

		if requestedDiff == nil {
			// Still looking for the decisive header. Skip minimum-difficulty
			// (DIFF1) headers by exact target equality, mirroring the Bridge's
			// target == MIN_DIFFICULTY_TARGET predicate. Their work is still
			// added to observedDiff above.
			if skipMinDifficulty &&
				header.Target().Cmp(minDifficultyTarget) == 0 {
				continue
			}

			if headerDiff.Cmp(currentEpochDifficulty) == 0 {
				requestedDiff = currentEpochDifficulty
			} else if headerDiff.Cmp(previousEpochDifficulty) == 0 {
				requestedDiff = previousEpochDifficulty
			} else {
				// The Bridge would revert with "Not at current or previous
				// difficulty". The transaction is either too fresh (its epoch
				// is not yet proven in the relay) or too old. Skip it; it may
				// be proven in the future.
				return 0, 0, proofSkipOutsideRelayRange, nil
			}

			totalDifficultyRequired = new(big.Int).Mul(
				requestedDiff,
				txProofDifficultyFactor,
			)
		}

		if observedDiff.Cmp(totalDifficultyRequired) >= 0 {
			return accumulatedConfirmations, headerCount, proofSkipNone, nil
		}
	}
}

// walletEvent is a type constraint representing wallet-related chain events.
type walletEvent interface {
	GetWalletPublicKeyHash() [20]byte
}

// uniqueWalletPublicKeyHashes parses the list of wallet-related events and
// returns a list of unique wallet public key hashes.
func uniqueWalletPublicKeyHashes[T walletEvent](events []T) [][20]byte {
	cache := make(map[string]struct{})
	var publicKeyHashes [][20]byte

	for _, event := range events {
		key := event.GetWalletPublicKeyHash()
		strKey := hex.EncodeToString(key[:])

		// Check for uniqueness
		if _, exists := cache[strKey]; !exists {
			cache[strKey] = struct{}{}
			publicKeyHashes = append(publicKeyHashes, key)
		}
	}

	return publicKeyHashes
}

// spvProofAssembler is a type representing a function that is used
// to assemble an SPV proof for the given transaction hash and confirmations
// count.
type spvProofAssembler func(
	transactionHash bitcoin.Hash,
	requiredConfirmations uint,
	btcChain bitcoin.Chain,
) (*bitcoin.Transaction, *bitcoin.SpvProof, error)
