/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface BridgeStubInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bank"
      | "contractReferences"
      | "ecdsaWalletRegistry"
      | "getRedemptionWatchtower"
      | "reimbursementPool"
      | "relay"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "bank", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "contractReferences",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ecdsaWalletRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRedemptionWatchtower",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reimbursementPool",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "relay", values?: undefined): string;

  decodeFunctionResult(functionFragment: "bank", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contractReferences",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ecdsaWalletRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRedemptionWatchtower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reimbursementPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "relay", data: BytesLike): Result;
}

export interface BridgeStub extends BaseContract {
  connect(runner?: ContractRunner | null): BridgeStub;
  waitForDeployment(): Promise<this>;

  interface: BridgeStubInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bank: TypedContractMethod<[], [string], "view">;

  contractReferences: TypedContractMethod<
    [],
    [
      [string, string, string, string] & {
        _bank: string;
        _relay: string;
        _ecdsaWalletRegistry: string;
        _reimbursementPool: string;
      }
    ],
    "view"
  >;

  ecdsaWalletRegistry: TypedContractMethod<[], [string], "view">;

  getRedemptionWatchtower: TypedContractMethod<[], [string], "view">;

  reimbursementPool: TypedContractMethod<[], [string], "view">;

  relay: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bank"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "contractReferences"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string] & {
        _bank: string;
        _relay: string;
        _ecdsaWalletRegistry: string;
        _reimbursementPool: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "ecdsaWalletRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRedemptionWatchtower"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reimbursementPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "relay"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
