/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../common";
import type { BridgeStub, BridgeStubInterface } from "../BridgeStub";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_bank",
        type: "address",
      },
      {
        internalType: "address",
        name: "_relay",
        type: "address",
      },
      {
        internalType: "address",
        name: "_ecdsaWalletRegistry",
        type: "address",
      },
      {
        internalType: "address",
        name: "_reimbursementPool",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "bank",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "contractReferences",
    outputs: [
      {
        internalType: "address",
        name: "_bank",
        type: "address",
      },
      {
        internalType: "address",
        name: "_relay",
        type: "address",
      },
      {
        internalType: "address",
        name: "_ecdsaWalletRegistry",
        type: "address",
      },
      {
        internalType: "address",
        name: "_reimbursementPool",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ecdsaWalletRegistry",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRedemptionWatchtower",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "reimbursementPool",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "relay",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161024d38038061024d83398101604081905261002f9161009e565b600080546001600160a01b039586166001600160a01b03199182161790915560018054948616948216949094179093556002805492851692841692909217909155600380549190931691161790556100f2565b80516001600160a01b038116811461009957600080fd5b919050565b600080600080608085870312156100b457600080fd5b6100bd85610082565b93506100cb60208601610082565b92506100d960408601610082565b91506100e760608601610082565b905092959194509250565b61014c806101016000396000f3fe608060405234801561001057600080fd5b50600436106100615760003560e01c8062ae616a146100665780635f3281ca1461009657806376cdb03b1461009d578063a9de2f3a146100b0578063b59589d1146100f0578063c09975cd14610103575b600080fd5b600254610079906001600160a01b031681565b6040516001600160a01b0390911681526020015b60405180910390f35b6000610079565b600054610079906001600160a01b031681565b600054600154600254600354604080516001600160a01b03958616815293851660208501529184169183019190915291909116606082015260800161008d565b600154610079906001600160a01b031681565b600354610079906001600160a01b03168156fea2646970667358221220b80790e921185d3944e7c11642f0a017efab06f84e75b3c097c1e97fd027285664736f6c63430008110033";

type BridgeStubConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BridgeStubConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BridgeStub__factory extends ContractFactory {
  constructor(...args: BridgeStubConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _bank: AddressLike,
    _relay: AddressLike,
    _ecdsaWalletRegistry: AddressLike,
    _reimbursementPool: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(
      _bank,
      _relay,
      _ecdsaWalletRegistry,
      _reimbursementPool,
      overrides || {}
    );
  }
  override deploy(
    _bank: AddressLike,
    _relay: AddressLike,
    _ecdsaWalletRegistry: AddressLike,
    _reimbursementPool: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(
      _bank,
      _relay,
      _ecdsaWalletRegistry,
      _reimbursementPool,
      overrides || {}
    ) as Promise<
      BridgeStub & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): BridgeStub__factory {
    return super.connect(runner) as BridgeStub__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BridgeStubInterface {
    return new Interface(_abi) as BridgeStubInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): BridgeStub {
    return new Contract(address, _abi, runner) as unknown as BridgeStub;
  }
}
